---
- name: Gather OS info and set facts
  hosts: all
  gather_facts: yes
  tasks:

    - name: Set OS fact
      set_fact:
        my_os: >-
          {% if ansible_os_family is defined %}
            {{ ansible_os_family }} {{ ansible_distribution }} {{ ansible_distribution_version }}
          {% elif ansible_facts['os_name'] is defined %}
            {{ ansible_facts['os_name'] }} {{ ansible_facts['os_version'] }}
          {% else %}
            Unknown OS
          {% endif %}

    - name: Set host info
      set_fact:
        host_info: "Inventory: {{ inventory_hostname }}, Hostname: {{ ansible_hostname }}, OS: {{ my_os }}, IP: {{ ansible_default_ipv4.address | default('N/A') }}"

    - name: Show host info
      debug:
        msg: "{{ host_info }}"

