---
# =========================================
# Playbook: system_report.yml
# Purpose: Collect system data + package & service compliance
# Supported OS: Debian/Ubuntu, Windows
# Output: ./reports/global_system_report.json
# =========================================

# -----------------------------
# PLAY 1: Collect system data
# -----------------------------
- name: Collect system data on supported hosts
  hosts: all
  gather_facts: yes

  tasks:

    # ---------------------------------
    # Skip unsupported OS
    # ---------------------------------
    - name: Skip unsupported OS hosts
      meta: end_host
      when: ansible_os_family not in ['Debian', 'Windows']

    # ---------------------------------
    # OS type
    # ---------------------------------
    - name: Set OS type
      set_fact:
        os_type: "{{ 'windows' if ansible_os_family == 'Windows' else 'linux' }}"

    # ---------------------------------
    # Disk space
    # ---------------------------------
    - name: Get disk space on Linux
      ansible.builtin.shell: df -h / | awk 'NR==2 {print $4}'
      register: linux_disk
      changed_when: false
      when: os_type == 'linux'

    - name: Get disk space on Windows
      ansible.windows.win_shell: (Get-PSDrive C).Free / 1GB -as [int]
      register: windows_disk
      changed_when: false
      when: os_type == 'windows'

    - name: Normalize disk space
      set_fact:
        disk_free: >-
          {{ linux_disk.stdout if os_type == 'linux'
             else windows_disk.stdout ~ ' GB' }}

    # ---------------------------------
    # PACKAGE COMPLIANCE — Debian
    # ---------------------------------
    - name: Collect installed packages (Debian)
      ansible.builtin.package_facts:
        manager: auto
      when: ansible_os_family == "Debian"

    - name: Evaluate Debian package compliance
      set_fact:
        package_compliance:
          curl: "{{ 'installed' if 'curl' in ansible_facts.packages else 'missing' }}"
          git: "{{ 'installed' if 'git' in ansible_facts.packages else 'missing' }}"
          vim: "{{ 'installed' if 'vim' in ansible_facts.packages else 'missing' }}"
      when: ansible_os_family == "Debian"

    # ---------------------------------
    # PACKAGE COMPLIANCE — Windows
    # ---------------------------------
    - name: Check Git in PATH (Windows)
      ansible.windows.win_shell: git --version
      register: git_check
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Windows"

    - name: Check Chocolatey
      ansible.windows.win_shell: Get-Command choco -ErrorAction SilentlyContinue
      register: choco_check
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Windows"

    - name: Collect Chocolatey packages
      ansible.windows.win_shell: choco list --local-only
      register: choco_packages
      changed_when: false
      failed_when: false
      when:
        - ansible_os_family == "Windows"
        - choco_check.stdout != ""

    - name: Evaluate Windows package compliance
      set_fact:
        package_compliance:
          git: "{{ 'installed' if git_check.rc == 0 else 'missing' }}"
          7zip: >-
            {{
              'installed'
              if choco_check.stdout != '' and '7zip' in choco_packages.stdout
              else 'missing'
            }}
      when: ansible_os_family == "Windows"

    # ---------------------------------
    # SERVICE COMPLIANCE — Debian
    # ---------------------------------
    - name: Collect services (Debian)
      ansible.builtin.service_facts:
      when: ansible_os_family == "Debian"

    - name: Evaluate Debian service compliance
      set_fact:
        service_compliance:
          ssh: >-
            {{
              'running'
              if ansible_facts.services['ssh.service'].state == 'running'
              else 'stopped'
            }}
      when: ansible_os_family == "Debian"

    # ---------------------------------
    # SERVICE COMPLIANCE — Windows
    # ---------------------------------
    - name: Get WinRM service info
      ansible.windows.win_service_info:
        name: WinRM
      register: winrm_service
      when: ansible_os_family == "Windows"

    - name: Evaluate WinRM service compliance
      set_fact:
        service_compliance:
          WinRM: >-
            {{
              'running'
              if winrm_service.services | length > 0
                 and winrm_service.services[0].state | lower in ['running', 'started']
              else 'stopped'
            }}
      when: ansible_os_family == "Windows"

    # ---------------------------------
    # Host status
    # ---------------------------------
    - name: Mark host as healthy
      set_fact:
        host_status: "healthy"

    # ---------------------------------
    # Build per-host report
    # ---------------------------------
    - name: Build system report
      set_fact:
        system_report:
          inventory_host: "{{ inventory_hostname }}"
          hostname: "{{ ansible_hostname }}"
          os_family: "{{ ansible_os_family }}"
          os_type: "{{ os_type }}"
          cpu_count: "{{ ansible_processor_vcpus | default('N/A') }}"
          memory_mb: "{{ ansible_memtotal_mb | default('N/A') }}"
          disk_free: "{{ disk_free }}"
          ip_address: >-
            {% if ansible_os_family == 'Windows' %}
            {{ ansible_ip_addresses | select('match', '^(10|172|192)') | list | first | default('N/A') }}
            {% else %}
            {{ ansible_default_ipv4.address | default('N/A') }}
            {% endif %}
          package_compliance: "{{ package_compliance | default({}) }}"
          service_compliance: "{{ service_compliance | default({}) }}"
          status: "{{ host_status }}"
          failure_reason: "N/A"

# -----------------------------
# PLAY 2: Aggregate reports
# -----------------------------
- name: Aggregate reports on controller
  hosts: localhost
  gather_facts: no
  run_once: true

  tasks:

    - name: Build global system report
      set_fact:
        global_system_report: >-
          {{
            groups['all']
            | map('extract', hostvars, 'system_report')
            | select('defined')
            | list
          }}

    - name: Ensure reports directory exists
      ansible.builtin.file:
        path: ./reports
        state: directory

    - name: Write global JSON report
      ansible.builtin.copy:
        content: "{{ global_system_report | to_nice_json }}"
        dest: ./reports/global_system_report.json

    - name: Show global report
      debug:
        var: global_system_report

