---
# =========================================
# Playbook: system_remediation.yml
# Purpose: Safe remediation with privilege awareness
# =========================================

- name: Remediate system compliance issues
  hosts: all
  gather_facts: yes

  tasks:

    # ---------------------------------
    # Skip unsupported OS
    # ---------------------------------
    - name: Skip unsupported OS hosts
      meta: end_host
      when: ansible_os_family not in ['Debian', 'Windows']

    # =================================
    # Debian remediation
    # =================================
    - name: Install required packages (Debian)
      ansible.builtin.apt:
        name:
          - curl
          - git
          - vim
        state: present
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: Ensure SSH service is running (Debian)
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: yes
      become: true
      when: ansible_os_family == "Debian"

    # =================================
    # Windows remediation (SAFE)
    # =================================

    - name: Check if running as Administrator (Windows)
      ansible.windows.win_shell: |
        ([Security.Principal.WindowsPrincipal] `
          [Security.Principal.WindowsIdentity]::GetCurrent()
        ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
      register: is_admin
      changed_when: false
      when: ansible_os_family == "Windows"

    - name: Check if Chocolatey is installed
      ansible.windows.win_shell: Get-Command choco -ErrorAction SilentlyContinue
      register: choco_check
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Windows"

    - name: Install Chocolatey (only if admin)
      ansible.windows.win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      when:
        - ansible_os_family == "Windows"
        - is_admin.stdout | trim == 'True'
        - choco_check.stdout == ""

    - name: Install Git (only if admin)
      ansible.windows.win_shell: choco install git -y
      when:
        - ansible_os_family == "Windows"
        - is_admin.stdout | trim == 'True'
        - choco_check.stdout != ""

    - name: Install 7zip (only if admin)
      ansible.windows.win_shell: choco install 7zip -y
      when:
        - ansible_os_family == "Windows"
        - is_admin.stdout | trim == 'True'
        - choco_check.stdout != ""

    - name: Ensure WinRM service is running
      ansible.windows.win_service:
        name: WinRM
        state: started
        start_mode: auto
      when: ansible_os_family == "Windows"

