---
# =========================================
# Playbook: system_remediation.yml
# Purpose: Remediate missing packages & services
# Supported OS: Debian/Ubuntu, Windows
# Safe for mixed OS environments
# =========================================

- name: Remediate system compliance issues
  hosts: all
  gather_facts: yes

  tasks:

    # ---------------------------------
    # Skip unsupported OS
    # ---------------------------------
    - name: Skip unsupported OS hosts
      meta: end_host
      when: ansible_os_family not in ['Debian', 'Windows']

    # =================================
    # Debian / Ubuntu remediation
    # =================================
    - name: Install required packages (Debian)
      ansible.builtin.apt:
        name:
          - curl
          - git
          - vim
        state: present
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: Ensure SSH service is running (Debian)
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: yes
      become: true
      when: ansible_os_family == "Debian"

    # =================================
    # Windows remediation
    # =================================

    - name: Check if Chocolatey is installed
      ansible.windows.win_shell: Get-Command choco -ErrorAction SilentlyContinue
      register: choco_check
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Windows"

    - name: Install Chocolatey if missing
      ansible.windows.win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      when:
        - ansible_os_family == "Windows"
        - choco_check.stdout == ""

    - name: Ensure Git is installed (Windows)
      ansible.windows.win_shell: |
        if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
          choco install git -y
        }
      when: ansible_os_family == "Windows"

    - name: Ensure 7zip is installed (Windows)
      ansible.windows.win_shell: |
        if (-not (Get-Command 7z -ErrorAction SilentlyContinue)) {
          choco install 7zip -y
        }
      when: ansible_os_family == "Windows"

    - name: Ensure WinRM service is running (Windows)
      ansible.windows.win_service:
        name: WinRM
        state: started
        start_mode: auto
      when: ansible_os_family == "Windows"

